#! /bin/bash

mkdir -p styles/vendor/foundation
if mv node_modules/zurb-foundation-5/scss styles/vendor/foundation; then
  rm -rf node_modules/zurb-foundation-5
else
  rm -rf styles/vendor/foundation
  mkdir -p styles/vendor/foundation
  mv node_modules/zurb-foundation-5/scss styles/vendor/foundation
  rm -rf node_modules/zurb-foundation-5
fi